/**
 * Query service — answers user questions from wiki content using the LLM,
 * and optionally persists the answer as a new wiki page via the job queue.
 */

import * as pagesRepo from '../db/repos/pages-repo';
import { readPageBySlug } from '../wiki/wiki-store';
import {
  generateStructuredOutput,
  streamTextResponse,
} from '../llm/provider-registry';
import {
  QueryResponseSchema,
  QUERY_SYSTEM_PROMPT,
  buildQueryUserPrompt,
} from '../llm/prompts/query-prompt';
import {
  createChangeset,
  validateChangeset,
  applyChangeset,
} from '../wiki/wiki-transaction';
import { wikiPathFromSlug, slugFromTitle } from '../wiki/page-identity';
import { serializeFrontmatter } from '../wiki/frontmatter';
import { registerHandler } from '../jobs/worker';
import type { QueryResult, Job } from '@/lib/contracts';

// Maximum number of FTS search results to load as context for the LLM
const TOP_N_FTS = 5;

export const NO_QUERY_CONTEXT_ANSWER =
  'No relevant content was found in the wiki to answer this question. Try ingesting more sources or rephrasing your query.';

export const QUERY_STREAM_SYSTEM_PROMPT = `${QUERY_SYSTEM_PROMPT}

## Streaming response mode
- Return answer text only.
- Do not include JSON, citation metadata, or a references block.
- Citations are generated by a separate post-processing step.`;

const QueryCitationsSchema = QueryResponseSchema.pick({ citations: true });

// ---------------------------------------------------------------------------
// Query context + streaming
// ---------------------------------------------------------------------------

export interface QueryContextPage {
  slug: string;
  title: string;
  content: string;
}

export function prepareQueryContext(question: string): QueryContextPage[] {
  const searchResults = pagesRepo.searchPages(question);
  const topResults = searchResults.slice(0, TOP_N_FTS);

  return topResults
    .map((r) => {
      const doc = readPageBySlug(r.page.slug);
      return {
        slug: r.page.slug,
        title: r.page.title,
        content: doc?.body ?? r.snippet,
      };
    })
    .filter((p) => p.content.trim().length > 0);
}

export function streamQueryAnswer(
  systemPrompt: string,
  question: string,
  context: QueryContextPage[],
  abortSignal?: AbortSignal,
) {
  return streamTextResponse(
    'query',
    systemPrompt,
    buildQueryUserPrompt(question, context),
    abortSignal,
  );
}

export async function generateQueryCitations(
  question: string,
  fullAnswer: string,
  context: QueryContextPage[],
): Promise<{ pageSlug: string; excerpt: string }[]> {
  const response = await generateStructuredOutput(
    'query',
    QueryCitationsSchema,
    QUERY_SYSTEM_PROMPT,
    `${buildQueryUserPrompt(question, context)}

## Draft answer to cite

<draft_answer>
${fullAnswer}
</draft_answer>

Return only the structured citations for the draft answer above. Do not rewrite the answer.`,
  );

  // Post-validate citations: check excerpts actually appear in the source pages
  return response.citations.map((c) => {
    const page = context.find((p) => p.slug === c.pageSlug);
    if (!page) return { ...c, excerpt: `[unverified] ${c.excerpt}` };
    const normalizedContent = page.content.toLowerCase().replace(/\s+/g, ' ');
    const normalizedExcerpt = c.excerpt.toLowerCase().replace(/\s+/g, ' ');
    const isVerified = normalizedContent.includes(normalizedExcerpt);
    return isVerified ? c : { ...c, excerpt: `[unverified] ${c.excerpt}` };
  });
}

// ---------------------------------------------------------------------------
// runQuery — one-shot mode (used by save-as-page and fallback)
// ---------------------------------------------------------------------------

export async function runQuery(question: string): Promise<QueryResult> {
  const context = prepareQueryContext(question);

  if (context.length === 0) {
    return {
      answer: NO_QUERY_CONTEXT_ANSWER,
      citations: [],
      savedAsPage: null,
    };
  }

  const answerStream = streamQueryAnswer(
    QUERY_STREAM_SYSTEM_PROMPT,
    question,
    context,
  );

  let answer = '';
  for await (const delta of answerStream.textStream) {
    answer += delta;
  }

  let citations: { pageSlug: string; excerpt: string }[] = [];
  try {
    citations = await generateQueryCitations(question, answer, context);
  } catch {
    citations = [];
  }

  return { answer, citations, savedAsPage: null };
}

// ---------------------------------------------------------------------------
// saveQueryAsPage — runs inside the worker to avoid concurrent vault writes
// ---------------------------------------------------------------------------

export async function saveQueryAsPage(
  answer: string,
  title: string,
  citations: { pageSlug: string; excerpt: string }[],
  jobId: string,
): Promise<string> {
  const slug = slugFromTitle(title);
  const now = new Date().toISOString();
  const wikiPath = wikiPathFromSlug(slug);

  const existing = pagesRepo.getPageBySlug(slug);
  if (existing) {
    throw new Error(
      `A page with slug "${slug}" already exists ("${existing.title}"). Choose a different title or update the existing page.`,
    );
  }

  const citationsSection =
    citations.length > 0
      ? [
          '',
          '## References',
          '',
          ...citations.map((c) => `- [[${c.pageSlug}]]: ${c.excerpt}`),
        ].join('\n')
      : '';

  const body = `${answer}${citationsSection}\n`;

  const content = serializeFrontmatter(
    {
      title,
      created: now,
      updated: now,
      tags: ['query-answer'],
      sources: citations.map((c) => c.pageSlug),
    },
    body,
  );

  const changeset = createChangeset(jobId, [
    { action: 'create', path: wikiPath, content },
  ]);

  const validation = validateChangeset(changeset);
  if (!validation.valid) {
    throw new Error(
      `Changeset validation failed: ${validation.errors.join('; ')}`,
    );
  }

  await applyChangeset(changeset);
  return slug;
}

// ---------------------------------------------------------------------------
// Worker handler for save-to-wiki jobs
// ---------------------------------------------------------------------------

async function runSaveToWikiJob(
  job: Job,
  emit: (type: string, message: string, data?: Record<string, unknown>) => void,
): Promise<Record<string, unknown>> {
  const params = JSON.parse(job.paramsJson) as {
    answer: string;
    title: string;
    citations: { pageSlug: string; excerpt: string }[];
  };

  emit('save:start', `Saving answer as wiki page: ${params.title}`);
  const slug = await saveQueryAsPage(params.answer, params.title, params.citations, job.id);
  emit('save:complete', `Saved as wiki page: ${slug}`, { slug });

  return { slug };
}

registerHandler('save-to-wiki', runSaveToWikiJob);
