/**
 * Query service — answers user questions from wiki content using the LLM,
 * and optionally persists the answer as a new wiki page via the job queue.
 *
 * Every code path is subject-scoped: search, citation context, and
 * save-as-page all operate within a single Subject.
 */

import * as pagesRepo from '../db/repos/pages-repo';
import * as subjectsRepo from '../db/repos/subjects-repo';
import { readPageInSubject } from '../wiki/wiki-store';
import {
  generateStructuredOutput,
  streamTextResponse,
} from '../llm/provider-registry';
import {
  QueryResponseSchema,
  QUERY_SYSTEM_PROMPT,
  buildQueryUserPrompt,
} from '../llm/prompts/query-prompt';
import { getWikiLanguage } from '../db/repos/settings-repo';
import type { PromptContext } from '../llm/prompts/prompt-context';
import {
  createChangeset,
  validateChangeset,
  applyChangeset,
} from '../wiki/wiki-transaction';
import { buildWikiPath, slugFromTitle } from '../wiki/page-identity';
import { serializeFrontmatter } from '../wiki/frontmatter';
import { registerHandler } from '../jobs/worker';
import type { QueryResult, Job, Subject, SubjectId } from '@/lib/contracts';

const TOP_N_FTS = 5;

export const NO_QUERY_CONTEXT_ANSWER =
  'No relevant content was found in this subject to answer the question. Try ingesting more sources, switching subjects, or rephrasing your query.';

export const QUERY_STREAM_SYSTEM_PROMPT = `${QUERY_SYSTEM_PROMPT}

## Streaming response mode
- Return answer text only.
- Do not include JSON, citation metadata, or a references block.
- Citations are generated by a separate post-processing step.`;

const QueryCitationsSchema = QueryResponseSchema.pick({ citations: true });

export interface QueryContextPage {
  slug: string;
  title: string;
  content: string;
  isCurrent?: boolean;
}

export function prepareQueryContext(
  question: string,
  subjectId: SubjectId,
  currentPageSlug?: string,
): QueryContextPage[] {
  const subject = subjectsRepo.getById(subjectId);
  if (!subject) return [];

  const contextBySlug = new Map<string, QueryContextPage>();

  if (currentPageSlug) {
    const page = pagesRepo.getPageBySlug(subjectId, currentPageSlug);
    const doc = readPageInSubject(subject.slug, currentPageSlug);
    if (page && doc && doc.body.trim().length > 0) {
      contextBySlug.set(currentPageSlug, {
        slug: currentPageSlug,
        title: page.title,
        content: doc.body,
        isCurrent: true,
      });
    }
  }

  const searchResults = pagesRepo.searchPages(subjectId, question);
  for (const r of searchResults.slice(0, TOP_N_FTS)) {
    if (contextBySlug.has(r.page.slug)) continue;
    const doc = readPageInSubject(subject.slug, r.page.slug);
    const content = doc?.body ?? r.snippet;
    if (content.trim().length === 0) continue;
    contextBySlug.set(r.page.slug, {
      slug: r.page.slug,
      title: r.page.title,
      content,
    });
  }

  return [...contextBySlug.values()];
}

function subjectCtxFrom(subject: Subject) {
  return {
    slug: subject.slug,
    name: subject.name,
    description: subject.description,
  };
}

export function streamQueryAnswer(
  systemPrompt: string,
  question: string,
  context: QueryContextPage[],
  subject: Subject,
  abortSignal?: AbortSignal,
  history: { role: 'user' | 'assistant'; content: string }[] = [],
) {
  const promptCtx: PromptContext = {
    language: getWikiLanguage(),
    subject: subjectCtxFrom(subject),
  };
  return streamTextResponse(
    'query',
    systemPrompt,
    buildQueryUserPrompt(question, context, promptCtx, history),
    abortSignal,
  );
}

export async function generateQueryCitations(
  question: string,
  fullAnswer: string,
  context: QueryContextPage[],
  subject: Subject,
): Promise<{ pageSlug: string; excerpt: string }[]> {
  const promptCtx: PromptContext = {
    language: getWikiLanguage(),
    subject: subjectCtxFrom(subject),
  };
  const response = await generateStructuredOutput(
    'query',
    QueryCitationsSchema,
    QUERY_SYSTEM_PROMPT,
    `${buildQueryUserPrompt(question, context, promptCtx)}

## Draft answer to cite

<draft_answer>
${fullAnswer}
</draft_answer>

Return only the structured citations for the draft answer above. Do not rewrite the answer.`,
  );

  return response.citations.map((c) => {
    const page = context.find((p) => p.slug === c.pageSlug);
    if (!page) return { ...c, excerpt: `[unverified] ${c.excerpt}` };
    const normalizedContent = page.content.toLowerCase().replace(/\s+/g, ' ');
    const normalizedExcerpt = c.excerpt.toLowerCase().replace(/\s+/g, ' ');
    const isVerified = normalizedContent.includes(normalizedExcerpt);
    return isVerified ? c : { ...c, excerpt: `[unverified] ${c.excerpt}` };
  });
}

export async function runQuery(
  question: string,
  subject: Subject,
  currentPageSlug?: string,
): Promise<QueryResult> {
  const context = prepareQueryContext(question, subject.id, currentPageSlug);

  if (context.length === 0) {
    return {
      answer: NO_QUERY_CONTEXT_ANSWER,
      citations: [],
      savedAsPage: null,
    };
  }

  const answerStream = streamQueryAnswer(
    QUERY_STREAM_SYSTEM_PROMPT,
    question,
    context,
    subject,
  );

  let answer = '';
  for await (const delta of answerStream.textStream) {
    answer += delta;
  }

  let citations: { pageSlug: string; excerpt: string }[] = [];
  try {
    citations = await generateQueryCitations(question, answer, context, subject);
  } catch {
    citations = [];
  }

  return { answer, citations, savedAsPage: null };
}

export async function saveQueryAsPage(
  answer: string,
  title: string,
  citations: { pageSlug: string; excerpt: string }[],
  subject: Subject,
  jobId: string,
): Promise<string> {
  const slug = slugFromTitle(title);
  const now = new Date().toISOString();
  const wikiPath = buildWikiPath(subject.slug, slug);

  const existing = pagesRepo.getPageBySlug(subject.id, slug);
  if (existing) {
    throw new Error(
      `A page with slug "${slug}" already exists in subject "${subject.slug}" ("${existing.title}"). Choose a different title or update the existing page.`,
    );
  }

  const citationsSection =
    citations.length > 0
      ? [
          '',
          '## References',
          '',
          ...citations.map((c) => `- [[${c.pageSlug}]]: ${c.excerpt}`),
        ].join('\n')
      : '';

  const body = `${answer}${citationsSection}\n`;

  const content = serializeFrontmatter(
    {
      title,
      created: now,
      updated: now,
      tags: ['query-answer'],
      sources: citations.map((c) => c.pageSlug),
    },
    body,
  );

  const changeset = createChangeset(jobId, subject, [
    { action: 'create', path: wikiPath, content },
  ]);

  const validation = validateChangeset(changeset);
  if (!validation.valid) {
    throw new Error(
      `Changeset validation failed: ${validation.errors.join('; ')}`,
    );
  }

  await applyChangeset(changeset);
  return slug;
}

async function runSaveToWikiJob(
  job: Job,
  emit: (type: string, message: string, data?: Record<string, unknown>) => void,
): Promise<Record<string, unknown>> {
  const params = JSON.parse(job.paramsJson) as {
    answer: string;
    title: string;
    citations: { pageSlug: string; excerpt: string }[];
    subjectId?: string;
  };

  const subjectId = params.subjectId ?? job.subjectId;
  if (!subjectId) {
    throw new Error('save-to-wiki job missing subjectId');
  }
  const subject = subjectsRepo.getById(subjectId);
  if (!subject) {
    throw new Error(`Subject ${subjectId} not found`);
  }

  emit('save:start', `Saving answer to subject "${subject.slug}" as page: ${params.title}`);
  const slug = await saveQueryAsPage(
    params.answer,
    params.title,
    params.citations,
    subject,
    job.id,
  );
  emit('save:complete', `Saved as wiki page: ${slug}`, { slug, subject: subject.slug });

  return { slug, subjectId: subject.id };
}

registerHandler('save-to-wiki', runSaveToWikiJob);
